# Generated by Django 6.0.6 on 2026-07-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='topic',
            field=models.CharField(max_length=150),
        ),
    ]
