# Generated by Django 6.0.6 on 2026-07-12 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_alter_exercise_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='source',
            field=models.CharField(choices=[('G', 'Generated'), ('S', 'Seed_dataset'), ('U', 'Uploaded')], default='G', max_length=1),
        ),
    ]
