# Generated by Django 6.0.6 on 2026-07-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='hints',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
