# Generated by Django 6.0.6 on 2026-07-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='duration',
        ),
        migrations.AddField(
            model_name='pin',
            name='mode',
            field=models.CharField(choices=[('A', 'AUTO'), ('M', 'MANUAL')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pin',
            name='user_difficulty',
            field=models.CharField(blank=True, choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=2, null=True),
        ),
    ]
