# Generated by Django 6.0.6 on 2026-07-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_remove_pin_duration_pin_mode_pin_user_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='common_misconception',
            field=models.TextField(blank=True, default=''),
        ),
    ]
